"""Deterministic tiny upstream producers for the empty-artifact ICASSP DAG test.

This fixture intentionally stops at claim-bearing *inputs*.  Primary figures,
claim synchronization, and the PDF are generated by the repository's real v3
producers in the end-to-end test.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
from typing import Any

import pandas as pd

from ecgcert import lineage
from ecgcert.data.manifest import DatasetManifest, ManifestRecord
from ecgcert.physics import LEADS
from ecgcert.protocol import deep_configuration_panel
from ecgcert.stage_gates import (
    json_artifact_bytes,
    make_review,
    merge_review,
    validate_gate,
)


SEGMENTS = ("QRS", "ST", "T")
METHOD_EFFECTS = {
    "lowrank": 0.12,
    "ridge": 0.10,
    "masked-unet": 0.08,
    "imputeecg": 0.06,
}


def _sha(path: Path) -> str:
    return lineage.artifact_sha256(path)


def _write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )


def _read_json(path: Path) -> dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return value


def _require_hash(summary: dict[str, Any], key: str, path: Path) -> None:
    if summary.get("input_sha256", {}).get(key) != _sha(path):
        raise ValueError(f"{key} lineage mismatch for {path}")


def _manifest_record(root: Path, cohort: str, index: int) -> ManifestRecord:
    record_id = f"{cohort}/record-{index:02d}"
    header = root / f"{record_id}.hea"
    signal = root / f"{record_id}.dat"
    header.parent.mkdir(parents=True, exist_ok=True)
    header.write_text(f"record-{index:02d} 12 500 32\n", encoding="utf-8")
    signal.write_bytes(bytes([index + 1]) * 64)
    return ManifestRecord(
        record_id=record_id,
        patient_id=f"{cohort}-patient-{index:02d}",
        relative_header=f"{record_id}.hea",
        header_sha256=_sha(header),
        signal_file=f"{record_id}.dat",
        signal_size_bytes=signal.stat().st_size,
        signal_sha256=_sha(signal),
    )


def manifests(output: Path) -> None:
    output.mkdir(parents=True, exist_ok=False)
    for cohort in ("ptbxl", "chapman", "cpsc2018"):
        data_root = (output / "tiny-data" / cohort).resolve()
        records = tuple(_manifest_record(data_root, cohort, index) for index in range(12))
        manifest = DatasetManifest(
            cohort=cohort,
            version="tiny-release-fixture-v1",
            source_url=f"https://example.invalid/{cohort}/tiny-v1",
            root=str(data_root),
            records=records,
            split_salt="ecgcert-icassp27-v1",
            patient_id_strategy="one_fixture_patient_per_record",
        )
        _write_json(output / f"{cohort}.json", manifest.to_dict())
        DatasetManifest.from_path(output / f"{cohort}.json").verify_files()


def rank_map(manifest_path: Path, output: Path) -> None:
    manifest = DatasetManifest.from_path(manifest_path)
    manifest.verify_files()
    output.mkdir(parents=True, exist_ok=False)
    rows: list[dict[str, Any]] = []
    for segment_index, segment in enumerate(SEGMENTS):
        for config_index, configuration in enumerate(deep_configuration_panel()):
            config_id = "+".join(configuration)
            for target_index, target in enumerate(LEADS):
                rows.append(
                    {
                        "segment": segment,
                        "configuration": config_id,
                        "target": target,
                        "target_observed": target in configuration,
                        "ambiguity_robust_mv": round(
                            0.01
                            + 0.002 * segment_index
                            + 0.0001 * config_index
                            + 0.00001 * target_index,
                            8,
                        ),
                    }
                )
    cells = pd.DataFrame(rows)
    cells_path = output / "map_cells.parquet"
    cells.to_parquet(cells_path, index=False, compression="zstd")
    _write_json(
        output / "summary.v3.json",
        {
            "schema_version": "tiny-robust-rank-map-v3",
            "input_sha256": {"ptbxl_manifest": _sha(manifest_path)},
            "artifacts_sha256": {"map_cells.parquet": _sha(cells_path)},
            "n_cells": len(cells),
        },
    )


def benchmark(manifest_path: Path, rank_maps: Path, output: Path) -> None:
    DatasetManifest.from_path(manifest_path).verify_files()
    map_path = rank_maps / "map_cells.parquet"
    map_summary_path = rank_maps / "summary.v3.json"
    map_summary = _read_json(map_summary_path)
    _require_hash(map_summary, "ptbxl_manifest", manifest_path)
    if map_summary.get("artifacts_sha256", {}).get("map_cells.parquet") != _sha(map_path):
        raise ValueError("rank-map artifact hash mismatch")
    output.mkdir(parents=True, exist_ok=False)
    rows = []
    for patient_index in range(8):
        for method, effect in METHOD_EFFECTS.items():
            for segment in SEGMENTS:
                rows.append(
                    {
                        "patient_id": f"ptbxl-patient-{patient_index:02d}",
                        "method": method,
                        "segment": segment,
                        "target": "V1",
                        "delta_r2": effect + patient_index * 0.0001,
                        "log_rmse": -2.0 + patient_index * 0.01,
                    }
                )
    metrics = pd.DataFrame(rows)
    metrics_path = output / "patient_metrics.parquet"
    metrics.to_parquet(metrics_path, index=False, compression="zstd")
    _write_json(
        output / "summary.v3.json",
        {
            "schema_version": "tiny-reconstruction-benchmark-v3",
            "input_sha256": {
                "ptbxl_manifest": _sha(manifest_path),
                "rank_map_summary": _sha(map_summary_path),
                "rank_map_cells": _sha(map_path),
            },
            "artifacts_sha256": {"patient_metrics.parquet": _sha(metrics_path)},
            "methods": sorted(METHOD_EFFECTS),
        },
    )


def external(
    *, cohort: str, manifest_path: Path, benchmark_dir: Path, output: Path
) -> None:
    DatasetManifest.from_path(manifest_path).verify_files()
    benchmark_metrics = benchmark_dir / "patient_metrics.parquet"
    benchmark_summary_path = benchmark_dir / "summary.v3.json"
    benchmark_summary = _read_json(benchmark_summary_path)
    if (
        benchmark_summary.get("artifacts_sha256", {}).get("patient_metrics.parquet")
        != _sha(benchmark_metrics)
    ):
        raise ValueError("benchmark artifact hash mismatch")
    offset = {"chapman": -0.02, "cpsc2018": -0.04}[cohort]
    output.mkdir(parents=True, exist_ok=False)
    rows = []
    for patient_index in range(6):
        for method, effect in METHOD_EFFECTS.items():
            rows.append(
                {
                    "patient_id": f"{cohort}-patient-{patient_index:02d}",
                    "method": method,
                    "segment": "QRS",
                    "target": "V1",
                    "delta_r2": effect + offset + patient_index * 0.0001,
                    "log_rmse": -1.8 + patient_index * 0.01,
                }
            )
    metrics = pd.DataFrame(rows)
    metrics_path = output / "patient_metrics.parquet"
    metrics.to_parquet(metrics_path, index=False, compression="zstd")
    _write_json(
        output / "summary.v3.json",
        {
            "schema_version": "tiny-zero-transfer-v3",
            "cohort": cohort,
            "input_sha256": {
                "target_manifest": _sha(manifest_path),
                "benchmark_summary": _sha(benchmark_summary_path),
                "benchmark_metrics": _sha(benchmark_metrics),
            },
            "artifacts_sha256": {"patient_metrics.parquet": _sha(metrics_path)},
        },
    )


def meta_analysis(
    *, rank_maps: Path, benchmark_dir: Path, chapman: Path, cpsc: Path, output: Path
) -> None:
    map_path = rank_maps / "map_cells.parquet"
    map_summary_path = rank_maps / "summary.v3.json"
    map_summary = _read_json(map_summary_path)
    if map_summary.get("artifacts_sha256", {}).get("map_cells.parquet") != _sha(map_path):
        raise ValueError("rank-map artifact changed before meta-analysis")
    benchmark_path = benchmark_dir / "patient_metrics.parquet"
    benchmark_summary_path = benchmark_dir / "summary.v3.json"
    benchmark_summary = _read_json(benchmark_summary_path)
    if (
        benchmark_summary.get("artifacts_sha256", {}).get("patient_metrics.parquet")
        != _sha(benchmark_path)
    ):
        raise ValueError("benchmark artifact changed before meta-analysis")
    sources = {
        "PTB-XL": benchmark_path,
        "chapman": chapman / "patient_metrics.parquet",
        "cpsc2018": cpsc / "patient_metrics.parquet",
    }
    for cohort, directory in (("chapman", chapman), ("cpsc2018", cpsc)):
        summary = _read_json(directory / "summary.v3.json")
        if summary.get("artifacts_sha256", {}).get("patient_metrics.parquet") != _sha(
            sources[cohort]
        ):
            raise ValueError(f"{cohort} external artifact changed before meta-analysis")
    effects = []
    for cohort, path in sources.items():
        point = float(pd.read_parquet(path)["delta_r2"].mean())
        effects.append({"cohort": cohort, "point": point, "ci95": [point - 0.01, point + 0.01]})
    output.mkdir(parents=True, exist_ok=False)
    effects_path = output / "effects.parquet"
    pd.DataFrame(effects).to_parquet(effects_path, index=False, compression="zstd")
    _write_json(
        output / "summary.v3.json",
        {
            "schema_version": "tiny-meta-analysis-v3",
            "input_sha256": {
                "rank_map_summary": _sha(map_summary_path),
                "rank_map_cells": _sha(map_path),
                "benchmark_summary": _sha(benchmark_summary_path),
                "benchmark_metrics": _sha(benchmark_path),
                "chapman_metrics": _sha(sources["chapman"]),
                "cpsc2018_metrics": _sha(sources["cpsc2018"]),
            },
            "artifacts_sha256": {"effects.parquet": _sha(effects_path)},
            "bootstrap_replicates": 2_000,
            "method_delta_r2": METHOD_EFFECTS,
        },
    )


def stage15_review(
    *, meta_dir: Path, private_key: Path, public_key: Path, output: Path
) -> None:
    effects_path = meta_dir / "effects.parquet"
    summary_path = meta_dir / "summary.v3.json"
    summary = _read_json(summary_path)
    if summary.get("artifacts_sha256", {}).get("effects.parquet") != _sha(effects_path):
        raise ValueError("meta-analysis effects changed before Stage 15")
    effects = {
        str(row.cohort): {"point": float(row.point), "ci95": list(row.ci95)}
        for row in pd.read_parquet(effects_path).itertuples(index=False)
    }
    evidence = {
        "ptbxl": effects["PTB-XL"],
        "external": {
            "chapman": effects["chapman"],
            "cpsc2018": effects["cpsc2018"],
        },
        "method_delta_r2": dict(METHOD_EFFECTS),
        "bootstrap_replicates": 2_000,
        "meta_summary_sha256": _sha(summary_path),
        "effects_sha256": _sha(effects_path),
    }
    now = datetime(2026, 7, 19, 0, 0, tzinfo=timezone.utc)
    gate: dict[str, Any] = {
        "schema_version": "arc-stage15-v3",
        "stage": 15,
        "status": "PENDING_USER_REVIEW",
        "eligible_for_proceed": True,
        "human_review_required": True,
        "review_deadline_hours": 24,
        "created_at": now.isoformat(),
        "automatic_reasons": [],
        "automatic_decision": "PROCEED",
        "meta_analysis_sha256": _sha(summary_path),
        "evidence": evidence,
        "evidence_sha256": lineage.canonical_sha256(evidence),
    }
    validate_gate(gate)
    gate_bytes = json_artifact_bytes(gate)
    gate_sha = hashlib.sha256(gate_bytes).hexdigest()
    review = make_review(
        gate,
        gate_sha256=gate_sha,
        reviewer="tiny-e2e-author",
        decision="PROCEED",
        private_key_path=private_key,
        public_key_path=public_key,
        repository_root=Path.cwd(),
        reviewed_at=now,
    )
    reviewed = merge_review(
        gate,
        review,
        gate_sha256=gate_sha,
        approval_sha256=hashlib.sha256(json_artifact_bytes(review)).hexdigest(),
        public_key_path=public_key,
    )
    output.mkdir(parents=True, exist_ok=False)
    (output / "decision.v3.json").write_bytes(json_artifact_bytes(reviewed))


def guard(allow_file: Path, output: Path) -> None:
    if not allow_file.is_file():
        raise RuntimeError("controlled release guard is still closed")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("guard passed\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "mode",
        choices=("manifests", "map", "benchmark", "external", "meta", "stage15", "guard"),
    )
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--rank-maps", type=Path)
    parser.add_argument("--benchmark", type=Path)
    parser.add_argument("--chapman", type=Path)
    parser.add_argument("--cpsc", type=Path)
    parser.add_argument("--cohort")
    parser.add_argument("--meta", type=Path)
    parser.add_argument("--private-key", type=Path)
    parser.add_argument("--public-key", type=Path)
    parser.add_argument("--allow-file", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if args.mode == "manifests":
        manifests(args.output)
    elif args.mode == "map":
        rank_map(args.manifest, args.output)
    elif args.mode == "benchmark":
        benchmark(args.manifest, args.rank_maps, args.output)
    elif args.mode == "external":
        external(
            cohort=args.cohort,
            manifest_path=args.manifest,
            benchmark_dir=args.benchmark,
            output=args.output,
        )
    elif args.mode == "meta":
        meta_analysis(
            rank_maps=args.rank_maps,
            benchmark_dir=args.benchmark,
            chapman=args.chapman,
            cpsc=args.cpsc,
            output=args.output,
        )
    elif args.mode == "stage15":
        stage15_review(
            meta_dir=args.meta,
            private_key=args.private_key,
            public_key=args.public_key,
            output=args.output,
        )
    else:
        guard(args.allow_file, args.output)


if __name__ == "__main__":
    main()
