"""Auto-generate the fair-baseline LaTeX table + inline macros from results JSON.

Reproducibility gate: no reconstruction number is hand-typed in the .tex. This reads
results/fair_baselines.json (per-timepoint waveform RMSE, identical protocol across
prior-mean / dipolar / ridge / U-Net) and writes:
  paper/auto/fair_baselines_table.tex   -- the booktabs tabular body
  paper/auto/fair_baselines_macros.tex  -- \\newcommand inline numbers

Run: python paper/emit_baseline_table.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AUTO = ROOT / "paper" / "auto"
CFG_TEX = {
    "{I,II,V2}": r"$\{$I,II,V2$\}$",
    "{I,II,V1,V3,V5}": r"$\{$I,II,V1,V3,V5$\}$",
    "limb-6": r"limb-6",
}
METHODS = [("prior_mean", "prior-mean"), ("dipolar", "dipolar"), ("ridge", "ridge"), ("unet", "U-Net")]
SEG = "QRS"


def _fmt(x):
    return f"{x:.3f}"


def main():
    d = json.loads((ROOT / "results" / "fair_baselines.json").read_text())
    cfgs = d["configs"]
    AUTO.mkdir(exist_ok=True)

    # ---- table (QRS, per-timepoint waveform RMSE) ----
    lines = [
        r"% AUTO-GENERATED by paper/emit_baseline_table.py -- do not edit by hand.",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"config & " + " & ".join(m[1] for m in METHODS) + r" \\",
        r"\midrule",
    ]
    for cname, ctex in CFG_TEX.items():
        cell = cfgs[cname]
        vals = {k: cell.get(k, {}).get(SEG, {}).get("rmse_mV") for k, _ in METHODS}
        best = min(v for v in vals.values() if v is not None)
        row = []
        for k, _ in METHODS:
            v = vals[k]
            s = _fmt(v) if v is not None else "--"
            if v is not None and abs(v - best) < 1e-9:
                s = r"\textbf{" + s + "}"
            row.append(s)
        lines.append(ctex + " & " + " & ".join(row) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    (AUTO / "fair_baselines_table.tex").write_text("\n".join(lines))

    # ---- inline macros ----
    def g(cfg, mth, seg):
        return cfgs[cfg][mth][seg]["rmse_mV"]

    span = "{I,II,V1,V3,V5}"
    m = [
        r"% AUTO-GENERATED by paper/emit_baseline_table.py",
        r"\newcommand{\NTestFair}{" + str(d["n_test"]) + "}",
        # spanning set: monotone ladder (QRS)
        r"\newcommand{\FairSpanPriorQRS}{" + _fmt(g(span, "prior_mean", "QRS")) + "}",
        r"\newcommand{\FairSpanDipQRS}{" + _fmt(g(span, "dipolar", "QRS")) + "}",
        r"\newcommand{\FairSpanRidgeQRS}{" + _fmt(g(span, "ridge", "QRS")) + "}",
        r"\newcommand{\FairSpanUnetQRS}{" + _fmt(g(span, "unet", "QRS")) + "}",
        # limb-6 collapse (QRS + ST)
        r"\newcommand{\FairLimbPriorQRS}{" + _fmt(g("limb-6", "prior_mean", "QRS")) + "}",
        r"\newcommand{\FairLimbRidgeQRS}{" + _fmt(g("limb-6", "ridge", "QRS")) + "}",
        r"\newcommand{\FairLimbUnetQRS}{" + _fmt(g("limb-6", "unet", "QRS")) + "}",
        r"\newcommand{\FairLimbUnetST}{" + _fmt(g("limb-6", "unet", "ST")) + "}",
        r"\newcommand{\FairSpanUnetST}{" + _fmt(g(span, "unet", "ST")) + "}",
        # U-Net degradation ratio limb/span (QRS)
        r"\newcommand{\FairUnetLimbSpanRatio}{"
        + f"{g('limb-6','unet','QRS')/g(span,'unet','QRS'):.2f}" + "}",
    ]
    # ---- ST-safety macros (graded eta gradient + full reconstructor matrix) ----
    sp = ROOT / "results" / "st_safety.json"
    if sp.exists():
        sd = json.loads(sp.read_text())
        eta = sd["certificate_eta_ST_precordial"]
        rec = sd["reconstructors"]

        def pct(x):
            return f"{100*x:.1f}"

        # LaTeX macro names must be letters only -> map V1..V6 to word suffixes
        _word = {"V1": "Vone", "V2": "Vtwo", "V3": "Vthree", "V4": "Vfour", "V5": "Vfive", "V6": "Vsix"}
        for lead, v in eta.items():
            m.append(r"\newcommand{\EtaST" + _word.get(lead, lead) + "}{" + f"{v:.3f}" + "}")
        m.append(r"\newcommand{\SafetyN}{" + str(sd.get("n_valid_delineation", sd.get("n_test"))) + "}")
        for name, r in rec.items():
            tag = name.capitalize()  # Dipolar / Ridge / Ols
            m.append(r"\newcommand{\Fab" + tag + "}{" + pct(r["fabricated_event_rate"]) + "}")
            m.append(r"\newcommand{\Msk" + tag + "}{" + pct(r["masked_event_rate"]) + "}")
            m.append(r"\newcommand{\Err" + tag + "}{" + f"{r['mean_st_error_mv']:.3f}" + "}")
            tot = r["fabricated_event_rate"] + r["masked_event_rate"]
            m.append(r"\newcommand{\Tot" + tag + "}{" + pct(tot) + "}")
        # reconstructor-invariant floor: min and max total wrong-event rate
        tots = [rec[n]["fabricated_event_rate"] + rec[n]["masked_event_rate"] for n in rec]
        m.append(r"\newcommand{\TotWrongLo}{" + pct(min(tots)) + "}")
        m.append(r"\newcommand{\TotWrongHi}{" + pct(max(tots)) + "}")

    # ---- calibration macros (headline group + honest worst subgroup) ----
    cp = ROOT / "results" / "tier2_conformal.json"
    if cp.exists():
        cd = json.loads(cp.read_text())
        # headline group: {I,II,V1,V3,V5} QRS/V2
        try:
            hg = cd["configs"]["{I,II,V1,V3,V5}"]["groups"]["QRS/V2"]
            m.append(r"\newcommand{\CalCov}{" + f"{hg['coverage']:.2f}" + "}")
            m.append(r"\newcommand{\CalCovLo}{" + f"{hg['coverage_ci'][0]:.2f}" + "}")
            m.append(r"\newcommand{\CalCovHi}{" + f"{hg['coverage_ci'][1]:.2f}" + "}")
            m.append(r"\newcommand{\CalWidth}{" + f"{hg['mean_width_mV']:.3f}" + "}")
        except Exception:
            pass
        # honest worst subgroup coverage across all (config,group,disease)
        worst = None
        for cname, cc in cd.get("configs", {}).items():
            for gk, gv in cc.get("groups", {}).items():
                for dis, dv in (gv.get("subgroup_coverage") or {}).items():
                    cov = dv.get("coverage")
                    if cov is not None and (worst is None or cov < worst[0]):
                        worst = (cov, dis, dv.get("n"), cname, gk)
        if worst:
            m.append(r"\newcommand{\WorstSubCov}{" + f"{worst[0]:.2f}" + "}")
            m.append(r"\newcommand{\WorstSubName}{" + str(worst[1]) + "}")
            m.append(r"\newcommand{\WorstSubN}{" + str(worst[2]) + "}")

    (AUTO / "fair_baselines_macros.tex").write_text("\n".join(m) + "\n")
    print("wrote", AUTO / "fair_baselines_table.tex")
    print("wrote", AUTO / "fair_baselines_macros.tex")
    print(f"  ladder QRS span: prior {g(span,'prior_mean','QRS'):.3f} -> dip "
          f"{g(span,'dipolar','QRS'):.3f} -> ridge {g(span,'ridge','QRS'):.3f} -> "
          f"unet {g(span,'unet','QRS'):.3f}")
    print(f"  limb-6 unet QRS {g('limb-6','unet','QRS'):.3f} = "
          f"{g('limb-6','unet','QRS')/g(span,'unet','QRS'):.2f}x the spanning-set unet")


if __name__ == "__main__":
    main()
