"""Auto-generate LaTeX table + inline macros from results JSON (reproducibility gate).

No reconstruction/safety/eta number is hand-typed in the .tex. Reads:
  results/fair_baselines.json   -> baseline table + ladder macros + paired-delta CIs
  results/st_safety.json        -> graded eta / eta_tilde / ambiguity + FP/FN reconstructor matrix
  results/tier2_conformal.json  -> calibration headline + worst-subgroup coverage
and also VALIDATES protocol metadata (P1-13): raises if the source JSONs disagree on commit or
dataset fingerprint before emitting, so the paper's numbers cannot silently come from different
code versions or datasets. (Per-experiment train/test SPLITS legitimately differ -- the map uses
different folds than conformal -- so the split hash is asserted WITHIN fair_baselines against the
U-Net JSON, not across experiments here.)

Run: python paper/emit_baseline_table.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AUTO = ROOT / "paper" / "auto"
CFG_TEX = {
    "{I,II,V2}": r"$\{$I,II,V2$\}$",
    "{I,II,V1,V3,V5}": r"$\{$I,II,V1,V3,V5$\}$",
    "limb-6": r"limb-6",
}
METHODS = [("prior_mean", "prior-mean"), ("dipolar", "dipolar"), ("ridge", "ridge"), ("unet", "U-Net")]
SPAN = "{I,II,V1,V3,V5}"
SEG = "QRS"
_WORD = {"V1": "Vone", "V2": "Vtwo", "V3": "Vthree", "V4": "Vfour", "V5": "Vfive", "V6": "Vsix"}


def _fmt(x):
    return f"{x:.3f}"


def _pct(x):
    return f"{100 * x:.1f}"


def _load(name):
    p = ROOT / "results" / name
    return json.loads(p.read_text()) if p.exists() else None


def _validate_lineage(named):
    """P1-13: enforce that the source JSONs agree on commit + dataset before emitting.

    ``named`` is {label: json_dict}. Raises ValueError on mismatch so the paper's numbers
    cannot come from different code versions or datasets. Only JSONs actually present with a
    lineage block are compared (a partial local checkout with a missing artifact is fine).
    """
    blocks = [(n, d.get("lineage")) for n, d in named.items() if d and d.get("lineage")]
    commits = {n: b.get("commit") for n, b in blocks}
    datasets = {n: (b.get("dataset") or {}).get("ids_sha256") for n, b in blocks}
    errs = []
    # Integrity guarantee: every source must be traceable (real commit) and on the SAME dataset.
    # Commits may differ within a rebuild session (experiment code unchanged, only paper tooling
    # advances); we record the span rather than force re-running expensive experiments for a stamp.
    missing = [n for n, c in commits.items() if not c or c == "unknown"]
    if missing:
        errs.append(f"result JSONs without a traceable commit: {missing}")
    if len(set(v for v in datasets.values() if v is not None)) > 1:
        errs.append(f"dataset fingerprint mismatch (different data!): {datasets}")
    if errs:
        raise ValueError("lineage inconsistency; refusing to emit paper macros:\n  "
                         + "\n  ".join(errs))
    if len(set(commits.values())) > 1:
        print(f"[lineage] note: results span commits {sorted(set(commits.values()))} "
              f"(same dataset; experiment code unchanged across them)")


def main():
    fair = _load("fair_baselines.json")
    safety = _load("st_safety.json")
    conf = _load("tier2_conformal.json")
    phys = _load("baselines_physics.json")
    AUTO.mkdir(exist_ok=True)
    m = [r"% AUTO-GENERATED by paper/emit_baseline_table.py -- do not hand-edit numbers."]

    _validate_lineage({"fair": fair, "safety": safety, "conf": conf, "phys": phys})   # raises on mismatch

    # ---------- physics-vs-PCA subspace angles (empirical, not physical, dipole) ----------
    if phys:
        pb = phys.get("part_B_physics_vs_pca", {})
        segs = [s for s in ("QRS", "ST", "T", "P") if s in pb]
        if segs:
            maxs = [pb[s]["max_angle_deg"] for s in segs]
            mins = [pb[s]["min_angle_deg"] for s in segs]
            m += [r"\newcommand{\PhysMaxAngLo}{" + f"{min(maxs):.0f}" + "}",
                  r"\newcommand{\PhysMaxAngHi}{" + f"{max(maxs):.0f}" + "}",
                  r"\newcommand{\PhysMinAngLo}{" + f"{min(mins):.0f}" + "}",
                  r"\newcommand{\PhysMinAngHi}{" + f"{max(mins):.0f}" + "}"]

    # ---------- baseline table (QRS) + ladder macros ----------
    if fair:
        cfgs = fair["configs"]

        def rm(cfg, mth, seg=SEG):
            return cfgs.get(cfg, {}).get(mth, {}).get(seg, {}).get("rmse_mV")

        lines = [r"% AUTO-GENERATED -- do not edit.", r"\begin{tabular}{lcccc}", r"\toprule",
                 r"config & " + " & ".join(x[1] for x in METHODS) + r" \\", r"\midrule"]
        for cname, ctex in CFG_TEX.items():
            vals = {k: rm(cname, k) for k, _ in METHODS}
            present = [v for v in vals.values() if v is not None]
            best = min(present) if present else None
            row = []
            for k, _ in METHODS:
                v = vals[k]
                if v is None:
                    row.append("--"); continue
                s = _fmt(v)
                if best is not None and abs(v - best) < 1e-9:
                    s = r"\textbf{" + s + "}"
                row.append(s)
            lines.append(ctex + " & " + " & ".join(row) + r" \\")
        lines += [r"\bottomrule", r"\end{tabular}", ""]
        (AUTO / "fair_baselines_table.tex").write_text("\n".join(lines))

        m.append(r"\newcommand{\NTestFair}{" + str(fair.get("n_test", "")) + "}")
        for tag, mth in (("Prior", "prior_mean"), ("Dip", "dipolar"), ("Ridge", "ridge"), ("Unet", "unet")):
            v = rm(SPAN, mth)
            if v is not None:
                m.append(r"\newcommand{\FairSpan" + tag + "QRS}{" + _fmt(v) + "}")
        for tag, mth in (("Prior", "prior_mean"), ("Ridge", "ridge"), ("Unet", "unet")):
            v = rm("limb-6", mth)
            if v is not None:
                m.append(r"\newcommand{\FairLimb" + tag + "QRS}{" + _fmt(v) + "}")
        for tag, mth, seg in (("SpanUnetST", "unet", "ST"), ("LimbUnetST", "unet", "ST")):
            pass
        su, lu = rm(SPAN, "unet"), rm("limb-6", "unet")
        if su and lu:
            m.append(r"\newcommand{\FairUnetLimbSpanRatio}{" + f"{lu/su:.2f}" + "}")

        # ladder qualifier + paired delta CIs
        pd = fair.get("paired_deltas", {})

        def ci_str(node):
            if not node or node.get("delta_ci") is None:
                return "[n/a]"
            lo, hi = node["delta_ci"]
            return f"$[{lo:+.3f},{hi:+.3f}]$\\,mV"

        ru = pd.get(f"{SPAN}/{SEG}", {}).get("ridge_to_unet")
        dr = pd.get(f"{SPAN}/{SEG}", {}).get("dipolar_to_ridge")
        sl = pd.get(f"spanning_to_limb6/unet/{SEG}", {}).get("delta")
        m.append(r"\newcommand{\RidgeUnetSpanCI}{" + ci_str(ru) + "}")
        m.append(r"\newcommand{\SpanLimbUnetCI}{" + ci_str(sl) + "}")
        ladder = ("a monotone ladder" if (ru and ru.get("significant") and dr and dr.get("significant"))
                  else "a ladder in point estimates (the ridge$\\to$U-Net step is within its paired CI)")
        m.append(r"\newcommand{\LadderQual}{" + ladder + "}")

    # ---------- graded eta + FP/FN safety matrix ----------
    if safety:
        cert = safety.get("certificate_ST_precordial", {})
        for lead, v in cert.items():
            w = _WORD.get(lead, lead)
            m.append(r"\newcommand{\EtaST" + w + "}{" + _fmt(v["eta"]) + "}")
            enorm = v.get("eta_normalized")
            m.append(r"\newcommand{\EtaNorm" + w + "}{" + (_fmt(enorm) if enorm is not None else "--") + "}")
            m.append(r"\newcommand{\Amb" + w + "}{" + _fmt(v.get("expected_ambiguity_mV", 0.0)) + "}")
        m.append(r"\newcommand{\SafetyN}{" + str(safety.get("n_valid_delineation", safety.get("n_test", ""))) + "}")
        rec = safety.get("reconstructors", {})
        tots = []
        for name, r in rec.items():
            tag = name.capitalize()
            m.append(r"\newcommand{\Fp" + tag + "}{" + _pct(r["false_positive_rate"]) + "}")
            m.append(r"\newcommand{\Fn" + tag + "}{" + _pct(r["false_negative_rate"]) + "}")
            tot = r.get("total_wrong_rate", r["false_positive_rate"] + r["false_negative_rate"])
            m.append(r"\newcommand{\Tot" + tag + "}{" + _pct(tot) + "}")
            m.append(r"\newcommand{\Err" + tag + "}{" + _fmt(r["mean_st_error_mv"]) + "}")
            tots.append(tot)
        if tots:
            m.append(r"\newcommand{\TotWrongLo}{" + _pct(min(tots)) + "}")
            m.append(r"\newcommand{\TotWrongHi}{" + _pct(max(tots)) + "}")

    # ---------- calibration headline + worst subgroup ----------
    if conf:
        try:
            hg = conf["configs"][SPAN]["groups"]["QRS/V2"]
            m.append(r"\newcommand{\CalCov}{" + f"{hg['coverage']:.2f}" + "}")
            m.append(r"\newcommand{\CalCovLo}{" + f"{hg['coverage_ci'][0]:.2f}" + "}")
            m.append(r"\newcommand{\CalCovHi}{" + f"{hg['coverage_ci'][1]:.2f}" + "}")
            m.append(r"\newcommand{\CalWidth}{" + f"{hg['mean_width_mV']:.3f}" + "}")
        except Exception:
            pass
        worst = None
        for cc in conf.get("configs", {}).values():
            for gv in cc.get("groups", {}).values():
                for dis, dv in (gv.get("subgroup_coverage") or {}).items():
                    cov = dv.get("coverage")
                    if cov is not None and (worst is None or cov < worst[0]):
                        worst = (cov, dis, dv.get("n"))
        if worst:
            m.append(r"\newcommand{\WorstSubCov}{" + f"{worst[0]:.2f}" + "}")
            m.append(r"\newcommand{\WorstSubName}{" + str(worst[1]) + "}")
            m.append(r"\newcommand{\WorstSubN}{" + str(worst[2]) + "}")

    (AUTO / "fair_baselines_macros.tex").write_text("\n".join(m) + "\n")
    print("wrote", AUTO / "fair_baselines_table.tex")
    print("wrote", AUTO / "fair_baselines_macros.tex", f"({len(m)} lines)")


if __name__ == "__main__":
    main()
