"""Auto-generate the fair-baseline LaTeX table + inline macros from results JSON.

Reproducibility gate: no reconstruction number is hand-typed in the .tex. This reads
results/fair_baselines.json (per-timepoint waveform RMSE, identical protocol across
prior-mean / dipolar / ridge / U-Net) and writes:
  paper/auto/fair_baselines_table.tex   -- the booktabs tabular body
  paper/auto/fair_baselines_macros.tex  -- \\newcommand inline numbers

Run: python paper/emit_baseline_table.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
AUTO = ROOT / "paper" / "auto"
CFG_TEX = {
    "{I,II,V2}": r"$\{$I,II,V2$\}$",
    "{I,II,V1,V3,V5}": r"$\{$I,II,V1,V3,V5$\}$",
    "limb-6": r"limb-6",
}
METHODS = [("prior_mean", "prior-mean"), ("dipolar", "dipolar"), ("ridge", "ridge"), ("unet", "U-Net")]
SEG = "QRS"


def _fmt(x):
    return f"{x:.3f}"


def main():
    d = json.loads((ROOT / "results" / "fair_baselines.json").read_text())
    cfgs = d["configs"]
    AUTO.mkdir(exist_ok=True)

    # ---- table (QRS, per-timepoint waveform RMSE) ----
    lines = [
        r"% AUTO-GENERATED by paper/emit_baseline_table.py -- do not edit by hand.",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"config & " + " & ".join(m[1] for m in METHODS) + r" \\",
        r"\midrule",
    ]
    for cname, ctex in CFG_TEX.items():
        cell = cfgs[cname]
        vals = {k: cell.get(k, {}).get(SEG, {}).get("rmse_mV") for k, _ in METHODS}
        best = min(v for v in vals.values() if v is not None)
        row = []
        for k, _ in METHODS:
            v = vals[k]
            s = _fmt(v) if v is not None else "--"
            if v is not None and abs(v - best) < 1e-9:
                s = r"\textbf{" + s + "}"
            row.append(s)
        lines.append(ctex + " & " + " & ".join(row) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    (AUTO / "fair_baselines_table.tex").write_text("\n".join(lines))

    # ---- inline macros ----
    def g(cfg, mth, seg):
        return cfgs[cfg][mth][seg]["rmse_mV"]

    span = "{I,II,V1,V3,V5}"
    m = [
        r"% AUTO-GENERATED by paper/emit_baseline_table.py",
        r"\newcommand{\NTestFair}{" + str(d["n_test"]) + "}",
        # spanning set: monotone ladder (QRS)
        r"\newcommand{\FairSpanPriorQRS}{" + _fmt(g(span, "prior_mean", "QRS")) + "}",
        r"\newcommand{\FairSpanDipQRS}{" + _fmt(g(span, "dipolar", "QRS")) + "}",
        r"\newcommand{\FairSpanRidgeQRS}{" + _fmt(g(span, "ridge", "QRS")) + "}",
        r"\newcommand{\FairSpanUnetQRS}{" + _fmt(g(span, "unet", "QRS")) + "}",
        # limb-6 collapse (QRS + ST)
        r"\newcommand{\FairLimbPriorQRS}{" + _fmt(g("limb-6", "prior_mean", "QRS")) + "}",
        r"\newcommand{\FairLimbRidgeQRS}{" + _fmt(g("limb-6", "ridge", "QRS")) + "}",
        r"\newcommand{\FairLimbUnetQRS}{" + _fmt(g("limb-6", "unet", "QRS")) + "}",
        r"\newcommand{\FairLimbUnetST}{" + _fmt(g("limb-6", "unet", "ST")) + "}",
        r"\newcommand{\FairSpanUnetST}{" + _fmt(g(span, "unet", "ST")) + "}",
        # U-Net degradation ratio limb/span (QRS)
        r"\newcommand{\FairUnetLimbSpanRatio}{"
        + f"{g('limb-6','unet','QRS')/g(span,'unet','QRS'):.2f}" + "}",
    ]
    (AUTO / "fair_baselines_macros.tex").write_text("\n".join(m) + "\n")
    print("wrote", AUTO / "fair_baselines_table.tex")
    print("wrote", AUTO / "fair_baselines_macros.tex")
    print(f"  ladder QRS span: prior {g(span,'prior_mean','QRS'):.3f} -> dip "
          f"{g(span,'dipolar','QRS'):.3f} -> ridge {g(span,'ridge','QRS'):.3f} -> "
          f"unet {g(span,'unet','QRS'):.3f}")
    print(f"  limb-6 unet QRS {g('limb-6','unet','QRS'):.3f} = "
          f"{g('limb-6','unet','QRS')/g(span,'unet','QRS'):.2f}x the spanning-set unet")


if __name__ == "__main__":
    main()
